site_name: FileSense
site_description: Modern file analysis and insights platform
site_url: https://ahhyoushh.github.io/FileSense/
repo_url: https://github.com/ahhyoushh/FileSense
repo_name: ahhyoushh/FileSense

docs_dir: wiki

theme:
  name: material
  
  palette:
    - scheme: slate
      primary: slate
      accent: blue
      toggle:
        icon: material/moon-waning-crescent
        name: Light mode
    
    - scheme: default
      primary: slate
      accent: blue
      toggle:
        icon: material/white-balance-sunny
        name: Dark mode

  features:
    # Navigation & UX
    - navigation.instant
    - navigation.instant.loading
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    
    # Search
    - search.suggest
    - search.highlight
    - search.share
    
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    
    # Appearance
    - toc.follow
    - header.autohide

font:
  text: Inter
  code: JetBrains Mono


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - toc:
      permalink: true
      permalink_class: headerlink

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Pipelines: pipelines.md
  - Metrics: metrics.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ahhyoushh/FileSense
      name: GitHub