title: "FileSense Docs"

# Use Minimal Mistakes via remote theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# GitHub Pages project site
url: "https://ahhyoushh.github.io"
baseurl: "/FileSense"       # project root, NOT /FileSense/wiki

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: wiki
