# docs/_config.yml
title: FileSense
description: FileSense documentation
baseurl: "/FileSense"     
url: "https://ahhyoushh.github.io"
paginate: 0

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "" 
    values:
      css: "/assets/css/custom.css"
