# docs/_config.yml
title: FileSense
description: FileSense documentation and blog
baseurl: "/FileSense"
url: "https://ahhyoushh.github.io"
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

search_enabled: true
permalink: pretty

# ensure remote theme plugin is available for local preview
plugins:
  - jekyll-remote-theme
